/**
 * Created by mma on 12/22/16.
 */
$(document).ready(function(){
    var owl4 = $('#owl4');
    owl4.owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:true,
                dots:false
            },
            600:{
                items:3,
                nav:false,
                dots:false
            },
            1000:{
                items:4,
                loop:true,
                dots:false
            }
        }
    })
    var owl3 = $('#owl3');
    owl3.owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:true,
                dots:false
            },
            600:{
                items:3,
                nav:false,
                dots:false
            },
            1000:{
                items:4,
                loop:true,
                dots:false
            }
        }
    })
    var owl2 = $('#owl2');
    owl2.owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:true,
                dots:false
            },
            600:{
                items:3,
                nav:false,
                dots:false
            },
            1000:{
                items:4,
                loop:true,
                dots:false
            }
        }
    })
    var owl1 = $('#owl1');
    owl1.owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:true,
                dots:false
            },
            600:{
                items:3,
                nav:false,
                dots:false
            },
            1000:{
                items:4,
                loop:true,
                dots:false
            }
        }
    })
});